language: objective-c
osx_image: xcode11.4
xcode_project: NFCSupport.xcodeproj # path to your xcodeproj folder
xcode_sdk: iphonesimulator

script:
   - pod lib lint --allow-warnings
   - xcodebuild clean test -scheme NFCSupport -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4.1'
